version: '3.8'
services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myroot
      POSTGRES_PASSWORD: myroot
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: myadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: myroot
    ports:
      - "5050:80" 
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  postgres-data:
  pgadmin-data:
